---
# Install spark packages

- name: unwanted packages are removed
  package:
    name: "{{ spark_packages_remove }}"
    state: absent
  become: true
  when: spark_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ spark_packages_repos }}"
    state: "{{ spark_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ spark_packages_prereq }}"
    state: "{{ spark_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ spark_packages_install }}"
    state: "{{ spark_packages_state }}"
  become: true
