---
# Template configuration files for spark

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ spark_templates_copy }}"
  when: spark_copy_templates
